# Claves de Supabase
SUPABASE_URL = "https://upmkrfbeopscsopuwdhj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwbWtyZmJlb3BzY3NvcHV3ZGhqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODc4NTA1NCwiZXhwIjoyMDY0MzYxMDU0fQ.xcoAxS8maPBorwimVoi6lirdtG8Wyt0RM2sW607Tp9w"

# Claves de Google Gemini
API_KEY_1 = "AIzaSyAVdHSWrN0NzgfWL6k1T2PZ2fkg0nRjn9I"
API_KEY_2 = "AIzaSyDd6NeEm_LgG6QNLgqI9VhK79LhOmDoIQw"
API_KEY_3 = "AIzaSyAVdHSWrN0NzgfWL6k1T2PZ2fkg0nRjn9I"

# Claves de tu S3 (Boto)
S3_ENDPOINT_URL = "https://upmkrfbeopscsopuwdhj.storage.supabase.co/storage/v1/s3"
S3_ACCESS_KEY = "5a60a59f942baa4ecd7866cc8c51970c"
S3_SECRET_KEY = "cc17fe9fc46bf72e3fe1646dfdefb716d65b0d239cec00e9acff6bcfb79f1e61"
S3_BUCKET = "db.json"
